name: konvo

services:
  frontend:
    image: nginx:alpine
    container_name: konvo-frontend
    ports:
      - "3000:8080"                     # http://localhost:3000
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: konvo-api
    expose:
      - "8000"                          # フロントから内部ネットワーク越しに参照
    volumes:
      - ./api:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

networks:
  default:
    name: konvo-net
